# Generated by Django 2.2.7 on 2019-12-23 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('UserID', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MobileNumber', models.CharField(max_length=10, unique=True)),
                ('Location', models.CharField(max_length=200)),
                ('GenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('UserType', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobs.Register')),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobs.Register')),
                ('Content', models.CharField(max_length=200)),
                ('File', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='UserType',
            field=models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='jobs.UserType'),
        ),
    ]
