# Generated by Django 2.2.7 on 2019-12-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191218_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='MobileNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='File',
            field=models.CharField(max_length=20),
        ),
    ]
